--Creacion usuarios

CREATE USER PC
       IDENTIFIED BY PC
       DEFAULT TABLESPACE PC_data
       QUOTA 10M ON PC_data
       TEMPORARY TABLESPACE temp
       QUOTA 5M ON system;
       
GRANT CONNECT TO PC;
GRANT CREATE PUBLIC SYNONYM TO PC;
GRANT CREATE SESSION TO PC;
GRANT CREATE TABLE TO PC;
GRANT CREATE ANY INDEX TO PC;
GRANT UNLIMITED TABLESPACE TO PC;

GRANT CREATE TRIGGER TO PC;
GRANT CREATE PROCEDURE TO PC;
GRANT CREATE VIEW TO PC;
GRANT CREATE SEQUENCE TO PC;

-------------------------------------------------------------------

CREATE USER PCADMIN
       IDENTIFIED BY PCADMIN
       DEFAULT TABLESPACE PC_data
       QUOTA 10M ON PC_data
       TEMPORARY TABLESPACE temp
       QUOTA 5M ON system;
       
GRANT CONNECT TO PCADMIN;
GRANT CREATE PUBLIC SYNONYM TO PCADMIN;
GRANT CREATE SESSION TO PCADMIN;
GRANT CREATE TABLE TO PCADMIN;
GRANT CREATE ANY INDEX TO PCADMIN;
GRANT UNLIMITED TABLESPACE TO PCADMIN;

GRANT CREATE TRIGGER TO PCADMIN;
GRANT CREATE PROCEDURE TO PCADMIN;
GRANT CREATE VIEW TO PCADMIN;
GRANT CREATE SEQUENCE TO PCADMIN;