--Drops para las tablas de PC
--Para drops de PC
SELECT 'DROP TABLE '||OWNER||'.'||table_name||';'
FROM all_all_tables
WHERE OWNER = 'PC';

--Para drops de PCADMIN
SELECT 'DROP TABLE '||OWNER||'.'||table_name||';'
FROM all_all_tables
WHERE OWNER = 'PCADMIN';

--Para eliminar constraints
SELECT 'ALTER TABLE '||OWNER||'.'||table_name||' DROP CONSTRAINT '||constraint_name||';' FROM all_constraints where owner ='PC';

--DROP TODO
DROP TABLE PC.NATIONALITY_X_PERSON;
DROP TABLE PC.NATIONALITY;
DROP TABLE PC.PERSON_USER;
DROP TABLE PC.USER_TYPE;
DROP TABLE PC.PARAMETER;
DROP TABLE PC.CATEGORY_X_PERSON;
DROP TABLE PC.PROPOSAL_COMMENT;
DROP TABLE PC.TELEPHONE;
DROP TABLE PC.EMAIL;
DROP TABLE PC.VOTE_X_PERSON;
DROP TABLE PC.PROPOSAL;
DROP TABLE PC.CATEGORY;
DROP TABLE PC.PERSON;
DROP TABLE PC.COMMUNITY;
DROP TABLE PC.DISTRICT;
DROP TABLE PC.CANTON;
DROP TABLE PC.PROVINCE;
DROP TABLE PC.COUNTRY;

DROP TABLE PCADMIN.PASSWORD_CHANGE;