GRANT SELECT, REFERENCES (id_user) ON PC.person_user TO PCADMIN;

GRANT ALL ON PC.country TO PCADMIN;
GRANT ALL ON PC.province TO PCADMIN;
GRANT ALL ON PC.canton TO PCADMIN;
GRANT ALL ON PC.district TO PCADMIN;
GRANT ALL ON PC.community TO PCADMIN;
GRANT ALL ON PC.proposal TO PCADMIN;
GRANT ALL ON PC.person TO PCADMIN;

GRANT SELECT ON PC.s_country TO PCADMIN;
GRANT SELECT ON PC.s_province TO PCADMIN;
GRANT SELECT ON PC.s_canton TO PCADMIN;
GRANT SELECT ON PC.s_district TO PCADMIN;
GRANT SELECT ON PC.s_community TO PCADMIN;
GRANT SELECT ON PC.s_proposal TO PCADMIN;

--Grants packages
GRANT EXECUTE ON PKG_CANTON TO PCADMIN;
GRANT EXECUTE ON PKG_COMMUNITY TO PCADMIN;
GRANT EXECUTE ON PKG_PROPOSAL TO PCADMIN;
GRANT EXECUTE ON PKG_NATIONALITY TO PCADMIN;
GRANT EXECUTE ON PKG_EMAIL TO PCADMIN;
GRANT EXECUTE ON PKG_COMMENT TO PCADMIN;
GRANT EXECUTE ON PKG_USER TO PCADMIN;
GRANT EXECUTE ON PKG_CATEGORY_X_PERSON TO PCADMIN;
GRANT EXECUTE ON PKG_NATIONALITY_X_PERSON TO PCADMIN;
GRANT EXECUTE ON PKG_COUNTRY TO PCADMIN;
GRANT EXECUTE ON PKG_PROVINCE TO PCADMIN;
GRANT EXECUTE ON PKG_DISTRICT TO PCADMIN;
GRANT EXECUTE ON PKG_CATEGORY TO PCADMIN;
GRANT EXECUTE ON PKG_USER_TYPE TO PCADMIN;
GRANT EXECUTE ON PKG_PERSON TO PCADMIN;
GRANT EXECUTE ON PKG_TELEPHONE TO PCADMIN;
GRANT EXECUTE ON PKG_VOTE_X_PERSON TO PCADMIN;
GRANT EXECUTE ON PKG_PARAMETER TO PCADMIN;
