GRANT SELECT, REFERENCES (id_user) ON TABLE PC.person_user TO PCADMIN;

GRANT ALL ON PC.country TO PCADMIN;
GRANT ALL ON PC.province TO PCADMIN;
GRANT ALL ON PC.canton TO PCADMIN;
GRANT ALL ON PC.district TO PCADMIN;
GRANT ALL ON PC.community TO PCADMIN;
GRANT ALL ON PC.proposal TO PCADMIN;

GRANT SELECT ON PC.s_country TO PCADMIN;
GRANT SELECT ON PC.s_province TO PCADMIN;
GRANT SELECT ON PC.s_canton TO PCADMIN;
GRANT SELECT ON PC.s_district TO PCADMIN;
GRANT SELECT ON PC.s_community TO PCADMIN;
GRANT SELECT ON PC.s_proposal TO PCADMIN;
