--Esquema PC

SELECT 'CREATE PUBLIC SYNONYM '||object_name||' FOR '||OWNER||'.'||object_name||';' 
FROM all_procedures
WHERE OWNER = 'PC'
AND object_type = 'PACKAGE'
AND subprogram_id = 0;

CREATE PUBLIC SYNONYM PKG_CANTON FOR PC.PKG_CANTON;
CREATE PUBLIC SYNONYM PKG_COMMUNITY FOR PC.PKG_COMMUNITY;
CREATE PUBLIC SYNONYM PKG_PROPOSAL FOR PC.PKG_PROPOSAL;
CREATE PUBLIC SYNONYM PKG_NATIONALITY FOR PC.PKG_NATIONALITY;
CREATE PUBLIC SYNONYM PKG_EMAIL FOR PC.PKG_EMAIL;
CREATE PUBLIC SYNONYM PKG_COMMENT FOR PC.PKG_COMMENT;
CREATE PUBLIC SYNONYM PKG_USER FOR PC.PKG_USER;
CREATE PUBLIC SYNONYM PKG_CATEGORY_X_PERSON FOR PC.PKG_CATEGORY_X_PERSON;
CREATE PUBLIC SYNONYM PKG_NATIONALITY_X_PERSON FOR PC.PKG_NATIONALITY_X_PERSON;
CREATE PUBLIC SYNONYM PKG_COUNTRY FOR PC.PKG_COUNTRY;
CREATE PUBLIC SYNONYM PKG_PROVINCE FOR PC.PKG_PROVINCE;
CREATE PUBLIC SYNONYM PKG_DISTRICT FOR PC.PKG_DISTRICT;
CREATE PUBLIC SYNONYM PKG_CATEGORY FOR PC.PKG_CATEGORY;
CREATE PUBLIC SYNONYM PKG_USER_TYPE FOR PC.PKG_USER_TYPE;
CREATE PUBLIC SYNONYM PKG_PERSON FOR PC.PKG_PERSON;
CREATE PUBLIC SYNONYM PKG_TELEPHONE FOR PC.PKG_TELEPHONE;
CREATE PUBLIC SYNONYM PKG_VOTE_X_PERSON FOR PC.PKG_VOTE_X_PERSON;
CREATE PUBLIC SYNONYM PKG_PARAMETER FOR PC.PKG_PARAMETER;