/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author mapac
 */
public class editProfile extends javax.swing.JFrame {

    /**
     * Creates new form editProfile
     */
    public editProfile() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        updateInformation = new javax.swing.JLabel();
        closeWindow = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        dateOfBithButton = new javax.swing.JButton();
        passwordButton = new javax.swing.JButton();
        idNumberButton = new javax.swing.JButton();
        phoneButton = new javax.swing.JButton();
        emailButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        idNumberLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        dateOfBirth = new javax.swing.JLabel();
        nameButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        nationalityButton = new javax.swing.JButton();
        locationButton = new javax.swing.JButton();
        photoButton = new javax.swing.JButton();
        userTypeLabel = new javax.swing.JLabel();
        nationalityLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateInformation.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        updateInformation.setText("Actualiza tu información");
        jPanel2.add(updateInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 40));

        closeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeWindow.png"))); // NOI18N
        closeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindowMouseClicked(evt);
            }
        });
        jPanel2.add(closeWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        dateOfBithButton.setBackground(new java.awt.Color(255, 255, 255));
        dateOfBithButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dateofbirth.png"))); // NOI18N
        dateOfBithButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(dateOfBithButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 130, 130));

        passwordButton.setBackground(new java.awt.Color(255, 255, 255));
        passwordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/password.png"))); // NOI18N
        passwordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        passwordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordButtonMouseClicked(evt);
            }
        });
        jPanel2.add(passwordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 130, 130));

        idNumberButton.setBackground(new java.awt.Color(255, 255, 255));
        idNumberButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/idNumber.png"))); // NOI18N
        idNumberButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idNumberButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idNumberButtonMouseClicked(evt);
            }
        });
        jPanel2.add(idNumberButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 130, 130));

        phoneButton.setBackground(new java.awt.Color(255, 255, 255));
        phoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phone.png"))); // NOI18N
        phoneButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        phoneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneButtonMouseClicked(evt);
            }
        });
        jPanel2.add(phoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 130, 130));

        emailButton.setBackground(new java.awt.Color(255, 255, 255));
        emailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/email.png"))); // NOI18N
        emailButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emailButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailButtonMouseClicked(evt);
            }
        });
        jPanel2.add(emailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 130, 130));

        nameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameLabel.setText("Nombre");
        jPanel2.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        idNumberLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        idNumberLabel.setText("Cédula o pasaporte");
        jPanel2.add(idNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 220, -1, -1));

        phoneLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        phoneLabel.setText("Teléfono");
        jPanel2.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 220, -1, -1));

        emailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        emailLabel.setText("Email");
        jPanel2.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 220, -1, -1));

        dateOfBirth.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dateOfBirth.setText("Fecha de nacimiento");
        jPanel2.add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 220, -1, -1));

        nameButton.setBackground(new java.awt.Color(255, 255, 255));
        nameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/name.png"))); // NOI18N
        nameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameButtonMouseClicked(evt);
            }
        });
        jPanel2.add(nameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 130));

        usersButton.setBackground(new java.awt.Color(255, 255, 255));
        usersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users.png"))); // NOI18N
        usersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(usersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, 130));

        nationalityButton.setBackground(new java.awt.Color(255, 255, 255));
        nationalityButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nationality.png"))); // NOI18N
        nationalityButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(nationalityButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 130, 130));

        locationButton.setBackground(new java.awt.Color(255, 255, 255));
        locationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        locationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(locationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 130, 130));

        photoButton.setBackground(new java.awt.Color(255, 255, 255));
        photoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/photo.png"))); // NOI18N
        photoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(photoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 130, 130));

        userTypeLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        userTypeLabel.setText("Tipo de usuario");
        jPanel2.add(userTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 420, -1, -1));

        nationalityLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nationalityLabel.setText("Nacionalidad");
        jPanel2.add(nationalityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 420, -1, -1));

        locationLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        locationLabel.setText("Localización");
        jPanel2.add(locationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 420, -1, -1));

        photoLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        photoLabel.setText("Foto");
        jPanel2.add(photoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 420, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        passwordLabel.setText("Contraseña");
        jPanel2.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 420, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowMouseClicked
        this.setVisible(false);
        citizenWindow login = new citizenWindow();
    }//GEN-LAST:event_closeWindowMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(loginWindow.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void nameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameButtonMouseClicked
        nameWindow name = new nameWindow();
    }//GEN-LAST:event_nameButtonMouseClicked

    private void idNumberButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idNumberButtonMouseClicked
        idNumberWindow idNumber = new idNumberWindow();
    }//GEN-LAST:event_idNumberButtonMouseClicked

    private void passwordButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordButtonMouseClicked
        passwordWindow password = new passwordWindow();
    }//GEN-LAST:event_passwordButtonMouseClicked

    private void phoneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneButtonMouseClicked
        telephoneWindow telephone = new telephoneWindow();
    }//GEN-LAST:event_phoneButtonMouseClicked

    private void emailButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailButtonMouseClicked
        emailWindow email = new emailWindow();
    }//GEN-LAST:event_emailButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeWindow;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JButton dateOfBithButton;
    private javax.swing.JButton emailButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton idNumberButton;
    private javax.swing.JLabel idNumberLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton locationButton;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton nameButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton nationalityButton;
    private javax.swing.JLabel nationalityLabel;
    private javax.swing.JButton passwordButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton phoneButton;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton photoButton;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel updateInformation;
    private javax.swing.JLabel userTypeLabel;
    private javax.swing.JButton usersButton;
    // End of variables declaration//GEN-END:variables
}
