/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author mapac
 */
public class editProfile extends javax.swing.JFrame {

    /**
     * Creates new form editProfile
     */
    public editProfile() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        updateInformation = new javax.swing.JLabel();
        closeWindow = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        sLastNameField = new javax.swing.JTextField();
        sLastName = new javax.swing.JLabel();
        fLastName = new javax.swing.JLabel();
        nameField1 = new javax.swing.JTextField();
        fLastNameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateInformation.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        updateInformation.setText("Actualiza tu información");
        jPanel2.add(updateInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 40));

        closeWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeWindow.png"))); // NOI18N
        closeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindowMouseClicked(evt);
            }
        });
        jPanel2.add(closeWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name.setText("Cambiar nombre");
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        sLastNameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(sLastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, -1));

        sLastName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sLastName.setText("Cambiar segundo apellido");
        jPanel2.add(sLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        fLastName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fLastName.setText("Cambiar primer apellido");
        jPanel2.add(fLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        nameField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(nameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, -1));

        fLastNameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel2.add(fLastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowMouseClicked
        this.setVisible(false);
        citizenWindow login = new citizenWindow();
    }//GEN-LAST:event_closeWindowMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(loginWindow.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeWindow;
    private javax.swing.JLabel fLastName;
    private javax.swing.JTextField fLastNameField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameField1;
    private javax.swing.JLabel sLastName;
    private javax.swing.JTextField sLastNameField;
    private javax.swing.JLabel updateInformation;
    // End of variables declaration//GEN-END:variables
}
