/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

/**
 *
 * @author mapac
 */
public class emailWindow extends javax.swing.JFrame {

    /** Creates new form emailWindow */
    public emailWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addTitle = new javax.swing.JLabel();
        addEmailLabel = new javax.swing.JLabel();
        addEmailField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        eliminateTitle = new javax.swing.JLabel();
        eliminateLabel = new javax.swing.JLabel();
        eliminateField = new javax.swing.JTextField();
        eliminateButton = new javax.swing.JButton();
        modifyTitle = new javax.swing.JLabel();
        oldEmailLabel = new javax.swing.JLabel();
        actualEmailLabel = new javax.swing.JLabel();
        oldEmailField = new javax.swing.JTextField();
        newEmailField = new javax.swing.JTextField();
        modifyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(476, 426));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/email.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        addTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addTitle.setText("Agregar");
        jPanel1.add(addTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));

        addEmailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addEmailLabel.setText("Agregar correo electrónico");
        jPanel1.add(addEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 20));

        addEmailField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(addEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 140, -1));

        addButton.setBackground(new java.awt.Color(0, 0, 102));
        addButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Agregar");
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 90, -1));

        eliminateTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        eliminateTitle.setText("Eliminar");
        jPanel1.add(eliminateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, -1));

        eliminateLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        eliminateLabel.setText("Eliminar correo electrónico");
        jPanel1.add(eliminateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        eliminateField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(eliminateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 140, -1));

        eliminateButton.setBackground(new java.awt.Color(0, 0, 102));
        eliminateButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        eliminateButton.setForeground(new java.awt.Color(255, 255, 255));
        eliminateButton.setText("Eliminar");
        eliminateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(eliminateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 90, -1));

        modifyTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        modifyTitle.setText("Modificar");
        jPanel1.add(modifyTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        oldEmailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        oldEmailLabel.setText("Correo electrónico anterior");
        jPanel1.add(oldEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, -1));

        actualEmailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        actualEmailLabel.setText("Correo electrónico actual");
        jPanel1.add(actualEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, -1));
        jPanel1.add(oldEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 257, 140, -1));

        newEmailField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(newEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 140, -1));

        modifyButton.setBackground(new java.awt.Color(0, 0, 102));
        modifyButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        modifyButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyButton.setText("Modificar");
        jPanel1.add(modifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        cancelButton.setBackground(new java.awt.Color(222, 4, 11));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminateButtonActionPerformed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emailWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualEmailLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addEmailField;
    private javax.swing.JLabel addEmailLabel;
    private javax.swing.JLabel addTitle;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton eliminateButton;
    private javax.swing.JTextField eliminateField;
    private javax.swing.JLabel eliminateLabel;
    private javax.swing.JLabel eliminateTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel modifyTitle;
    private javax.swing.JTextField newEmailField;
    private javax.swing.JTextField oldEmailField;
    private javax.swing.JLabel oldEmailLabel;
    // End of variables declaration//GEN-END:variables

}
