/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Connect.ConnectDB;
import Utils.Global;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mapac
 */
public class locationWindow extends javax.swing.JFrame {

    /**
     * Creates new form locationWindow
     */
    public locationWindow() throws SQLException {
        initComponents();
        fillCountriesComboBox();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    private void fillCountriesComboBox() throws SQLException
    {
        ConnectDB.getCountries();
        for (int countryNumber = 0; countryNumber < Global.countriesInfo.size(); countryNumber++)
        {
            countryComboBox.addItem(Global.countriesInfo.get(countryNumber).getName());
        }
    }
    
    private void fillProvincesComboBox(int id_country) throws SQLException
    {
        ConnectDB.getProvincesFromCountry(id_country);
        provinceComboBox.removeAllItems();
        for (int provinceNumber = 0; provinceNumber < Global.provincesInfo.size(); provinceNumber++)
        {
            provinceComboBox.addItem(Global.provincesInfo.get(provinceNumber).getName());
        }
    }
    
    private void fillCantonsComboBox(int id_province) throws SQLException
    {
        ConnectDB.getCantonsFromProvince(id_province);
        cantonComboBox.removeAllItems();
        for (int cantonNumber = 0; cantonNumber < Global.cantonsInfo.size(); cantonNumber++)
        {
            cantonComboBox.addItem(Global.cantonsInfo.get(cantonNumber).getName());
        }
    }
    
    private void fillDistrictsComboBox(int id_canton) throws SQLException
    {
        ConnectDB.getDistrictsFromCanton(id_canton);
        districtComboBox.removeAllItems();
        for (int districtNumber = 0; districtNumber < Global.districtsInfo.size(); districtNumber++)
        {
            districtComboBox.addItem(Global.districtsInfo.get(districtNumber).getName());
        }
    }
    
    private void fillCommunitiesComboBox(int id_district) throws SQLException
    {
        ConnectDB.getCommunitiesFromDistrict(id_district);
        communityComboBox.removeAllItems();
        for (int commNumber = 0; commNumber < Global.communitiesInfo.size(); commNumber++)
        {
            communityComboBox.addItem(Global.communitiesInfo.get(commNumber).getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconLocation = new javax.swing.JLabel();
        locationTitle = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        provinceLabel = new javax.swing.JLabel();
        cantonLabel = new javax.swing.JLabel();
        districtLabel = new javax.swing.JLabel();
        communityLabel = new javax.swing.JLabel();
        countryComboBox = new javax.swing.JComboBox<>();
        provinceComboBox = new javax.swing.JComboBox<>();
        cantonComboBox = new javax.swing.JComboBox<>();
        districtComboBox = new javax.swing.JComboBox<>();
        communityComboBox = new javax.swing.JComboBox<>();
        cancelButton1 = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        jPanel1.add(iconLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        locationTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        locationTitle.setText("Elegir ubicación");
        jPanel1.add(locationTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        countryLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        countryLabel.setText("País");
        jPanel1.add(countryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 40, -1));

        provinceLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        provinceLabel.setText("Provincia");
        jPanel1.add(provinceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cantonLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cantonLabel.setText("Cantón");
        jPanel1.add(cantonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        districtLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        districtLabel.setText("Distrito");
        jPanel1.add(districtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        communityLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        communityLabel.setText("Comunidad");
        jPanel1.add(communityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        countryComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        countryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(countryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 48, 110, -1));

        provinceComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        provinceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(provinceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 88, 110, -1));

        cantonComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cantonComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(cantonComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 128, 110, -1));

        districtComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        districtComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(districtComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 168, 110, -1));

        communityComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(communityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 110, -1));

        cancelButton1.setBackground(new java.awt.Color(222, 4, 11));
        cancelButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelButton1.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton1.setText("Cancelar");
        cancelButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButton1MouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        acceptButton.setBackground(new java.awt.Color(16, 123, 16));
        acceptButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        acceptButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptButton.setText("Aceptar");
        acceptButton.setPreferredSize(new java.awt.Dimension(89, 25));
        acceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptButtonMouseClicked(evt);
            }
        });
        jPanel1.add(acceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButton1MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_cancelButton1MouseClicked

    private void countryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryComboBoxActionPerformed
        try {
            fillProvincesComboBox(Global.countriesInfo.get(countryComboBox.getSelectedIndex()).getId());
        } catch (SQLException ex) {
            Logger.getLogger(registerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_countryComboBoxActionPerformed

    private void provinceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceComboBoxActionPerformed
        try {
            if (provinceComboBox.getSelectedItem() != null)
                fillCantonsComboBox(Global.provincesInfo.get(provinceComboBox.getSelectedIndex()).getId());
        } catch (SQLException ex) {
            Logger.getLogger(registerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_provinceComboBoxActionPerformed

    private void cantonComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonComboBoxActionPerformed
        try {
            if (cantonComboBox.getSelectedItem() != null)
                fillDistrictsComboBox(Global.cantonsInfo.get(cantonComboBox.getSelectedIndex()).getId());
        } catch (SQLException ex) {
            Logger.getLogger(registerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cantonComboBoxActionPerformed

    private void districtComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtComboBoxActionPerformed
        try {
            if (districtComboBox.getSelectedItem() != null)
                fillCommunitiesComboBox(Global.districtsInfo.get(districtComboBox.getSelectedIndex()).getId());
        } catch (SQLException ex) {
            Logger.getLogger(registerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_districtComboBoxActionPerformed

    private void acceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptButtonMouseClicked
        try {
            int id_community = Global.communitiesInfo.get(communityComboBox.getSelectedIndex()).getId();
            ConnectDB.updatePersonLocation(Global.id_person,id_community);
            if (Global.update_result == 1) JOptionPane.showMessageDialog(this,"Se ha modificado la localización","Modificación exitosa",JOptionPane.INFORMATION_MESSAGE);
            else JOptionPane.showMessageDialog(this,"No se ha podido modificar la localización","Error de modificación",JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(locationWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_acceptButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(locationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(locationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(locationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(locationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new locationWindow().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(locationWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JComboBox<String> cantonComboBox;
    private javax.swing.JLabel cantonLabel;
    private javax.swing.JComboBox<String> communityComboBox;
    private javax.swing.JLabel communityLabel;
    private javax.swing.JComboBox<String> countryComboBox;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JComboBox<String> districtComboBox;
    private javax.swing.JLabel districtLabel;
    private javax.swing.JLabel iconLocation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel locationTitle;
    private javax.swing.JComboBox<String> provinceComboBox;
    private javax.swing.JLabel provinceLabel;
    // End of variables declaration//GEN-END:variables
}
