/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Connect.ConnectDB;
import Utils.Global;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mapac
 */
public class nameWindow extends javax.swing.JFrame {

    /**
     * Creates new form nameWindow
     */
    public nameWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconName = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        fLastNameField = new javax.swing.JTextField();
        fLastName = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        sLastName = new javax.swing.JLabel();
        sLastNameField = new javax.swing.JTextField();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/name.png"))); // NOI18N
        jPanel1.add(iconName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 90, 110));

        nameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameLabel.setText("Cambiar nombre");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        fLastNameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(fLastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 120, -1));

        fLastName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fLastName.setText("Cambiar primer apellido");
        jPanel1.add(fLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        nameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 17, 120, -1));

        sLastName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sLastName.setText("Cambiar segundo apellido");
        jPanel1.add(sLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, -1, -1));

        sLastNameField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(sLastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 120, -1));

        acceptButton.setBackground(new java.awt.Color(16, 123, 16));
        acceptButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        acceptButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptButton.setText("Aceptar");
        acceptButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptButtonMouseClicked(evt);
            }
        });
        jPanel1.add(acceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 90, -1));

        cancelButton.setBackground(new java.awt.Color(222, 4, 11));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -5, 440, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void acceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptButtonMouseClicked
       String name = nameField.getText();
       String firstLName = fLastNameField.getText();
       String secLName = sLastNameField.getText();
       if(!"".equals(name) && !Global.hasNumbers(name)){
           try {
               ConnectDB.updatePersonName(Global.id_person,name);
               if (Global.update_result==1) JOptionPane.showMessageDialog(this, "El nombre ha sido actualizado","Actualización exitosa", JOptionPane.INFORMATION_MESSAGE);
               else JOptionPane.showMessageDialog(this, "No es posible modificar el nombre","Error de cambio", JOptionPane.ERROR_MESSAGE);
           } catch (SQLException ex) {
               Logger.getLogger(nameWindow.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       else JOptionPane.showMessageDialog(this, "No es posible modificar el nombre","Error de cambio", JOptionPane.ERROR_MESSAGE);
       if (!"".equals(firstLName) && !Global.hasNumbers(firstLName)){
           try {
               ConnectDB.updatePersonFirstLastName(Global.id_person,firstLName);
               if (Global.update_result==1) JOptionPane.showMessageDialog(this, "El primer apellido ha sido actualizado","Actualización exitosa", JOptionPane.INFORMATION_MESSAGE);
               else JOptionPane.showMessageDialog(this, "No es posible modificar el primer apellido","Error de cambio", JOptionPane.ERROR_MESSAGE);
           } catch (SQLException ex) {
               Logger.getLogger(nameWindow.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       else JOptionPane.showMessageDialog(this, "No es posible modificar el primer apellido","Error de cambio", JOptionPane.ERROR_MESSAGE);
       if (!"".equals(secLName) && !Global.hasNumbers(secLName)){
           try {
               ConnectDB.updatePersonSecLastName(Global.id_person,secLName);
               if (Global.update_result==1) JOptionPane.showMessageDialog(this, "El segundo apellido ha sido actualizado","Actualización exitosa", JOptionPane.INFORMATION_MESSAGE);
               else JOptionPane.showMessageDialog(this, "No es posible modificar el segundo apellido","Error de cambio", JOptionPane.ERROR_MESSAGE);
           } catch (SQLException ex) {
               Logger.getLogger(nameWindow.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       else JOptionPane.showMessageDialog(this, "No es posible modificar el segundo apellido","Error de cambio", JOptionPane.ERROR_MESSAGE);
       nameField.setText("");
       fLastNameField.setText("");
       sLastNameField.setText("");
       this.setVisible(false);
    }//GEN-LAST:event_acceptButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel fLastName;
    private javax.swing.JTextField fLastNameField;
    private javax.swing.JLabel iconName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel sLastName;
    private javax.swing.JTextField sLastNameField;
    // End of variables declaration//GEN-END:variables
}
