/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Connect.ConnectDB;
import Utils.Global;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lin
 */
public class photoChangeWindow extends javax.swing.JFrame {

    /**
     * Creates new form photoChangeWindow
     */
    public photoChangeWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPhoto = new javax.swing.JLabel();
        labelPreviewPhoto = new javax.swing.JLabel();
        selectPhoto = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPhoto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelPhoto.setText("Nueva foto de perfil");
        jPanel1.add(labelPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, -1));

        labelPreviewPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        jPanel1.add(labelPreviewPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 128, 128));

        selectPhoto.setBackground(new java.awt.Color(0, 0, 102));
        selectPhoto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        selectPhoto.setForeground(new java.awt.Color(255, 255, 255));
        selectPhoto.setText("Seleccionar");
        selectPhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPhotoActionPerformed(evt);
            }
        });
        jPanel1.add(selectPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        cancelButton.setBackground(new java.awt.Color(222, 4, 11));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        acceptButton.setBackground(new java.awt.Color(16, 123, 16));
        acceptButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        acceptButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptButton.setText("Aceptar");
        acceptButton.setPreferredSize(new java.awt.Dimension(89, 25));
        acceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptButtonMouseClicked(evt);
            }
        });
        jPanel1.add(acceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void acceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptButtonMouseClicked
        if (Global.photoChooser.getSelectedFile() == null)
        {
            JOptionPane.showMessageDialog(this,"No se ha modificado la foto de perfil","Error de modificación",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                String photo = Global.photoChooser.getSelectedFile().getName();
                ConnectDB.updatePersonProfilePicture(Global.id_person, photo);
                if (Global.update_result == 1) JOptionPane.showMessageDialog(this,"Se ha modificado la foto de perfil","Modificación exitosa",JOptionPane.INFORMATION_MESSAGE);
                else JOptionPane.showMessageDialog(this,"No se ha modificado la foto de perfil","Error de modificación",JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(photoChangeWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_acceptButtonMouseClicked

    private void selectPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPhotoActionPerformed
        Global.photoChooser.setDialogTitle("Seleccionar foto de perfil");
        Global.photoChooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png"));
        if (Global.photoChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            labelPreviewPhoto.setIcon(new ImageIcon(Global.photoChooser.getSelectedFile().toString())); 
        }
    }//GEN-LAST:event_selectPhotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(photoChangeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(photoChangeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(photoChangeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(photoChangeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new photoChangeWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPhoto;
    private javax.swing.JLabel labelPreviewPhoto;
    private javax.swing.JButton selectPhoto;
    // End of variables declaration//GEN-END:variables
}
