/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Connect.ConnectDB;
import Utils.Global;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lin
 */
public class registerProposal extends javax.swing.JFrame {

    /**
     * Creates new form registerProposal
     */
    public registerProposal() throws SQLException {
        initComponents();
        fillCategoriesComboBox();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    private void fillCategoriesComboBox() throws SQLException
    {
        ConnectDB.getCategories();
        for (int categoryNumber = 0; categoryNumber < Global.categoriesInfo.size(); categoryNumber++)
        {
            categoryComboBox.addItem(Global.categoriesInfo.get(categoryNumber).getName());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        descriptionField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        budgetField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Categoría");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        descriptionField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(descriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 310, 170));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Título de propuesta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Presupuesto Aproximado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        titleField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(titleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 310, 30));

        budgetField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(budgetField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 310, 30));

        registerButton.setBackground(new java.awt.Color(16, 123, 16));
        registerButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Registrar");
        registerButton.setPreferredSize(new java.awt.Dimension(89, 25));
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 110, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Descripción");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        categoryComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(categoryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 310, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 540));

        pack();
    }// </editor-fold>                        

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {                                            
        String title = titleField.getText();
        String budg = budgetField.getText();
        String description = descriptionField.getText();
        int catCode = Global.categoriesInfo.get(categoryComboBox.getSelectedIndex()).getId();
        if (!Global.hasNumbers(title) && !"".equals(title) && !"".equals(budg) && !"".equals(description) && Global.isNumeric(budg))
        {
            int aproxBud = Integer.valueOf(budg);
            try {
                ConnectDB.registerProposal(title,aproxBud, description,catCode,Global.id_person);
                if (Global.insert_result == 1) JOptionPane.showMessageDialog(this,"Se ha registrado la propuesta","Registro exitoso",JOptionPane.INFORMATION_MESSAGE);
                else JOptionPane.showMessageDialog(this,"No se ha registrado la propuesta","Error de regisro",JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(registerProposal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else JOptionPane.showMessageDialog(this,"No se ha registrado la propuesta","Error de regisro",JOptionPane.ERROR_MESSAGE);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerProposal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerProposal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerProposal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerProposal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new registerProposal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(registerProposal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField budgetField;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField titleField;
    // End of variables declaration                   
}
